require: sudo
language: node_js
services:
  - docker
script: 
  docker build -t alvarollmenezes/mockupagenda . && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push alvarollmenezes/mockupagenda
# deploy:
#   provider: script
#   script: docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push alvarollmenezes/mockupagenda
#   on:
#     branch: publish
